name: update

on:
  push:
    branches:
      - main
      - qa
      - production

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Download google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "${GOOGLE_SERVICES_JSON}" > ./assets/google-services.json

      - name: Get Latest Commit Message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          # Sanitize commit message by removing or escaping problematic characters
          SANITIZED_COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '\n' | sed 's/[^a-zA-Z0-9 ]/_/g')
          echo "Sanitized Commit Message: $SANITIZED_COMMIT_MESSAGE"
          echo "commit_message=$SANITIZED_COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Run EAS Update
        env:
          EAS_UPDATE_URL: ${{ secrets.EAS_UPDATE_URL }}
          GOOGLE_SERVICES_JSON: "./assets/google-services.json"
          COMMIT_MESSAGE: ${{ env.commit_message }}
          EXPO_PUBLIC_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_CLIENT_ID }}
        run: |
          if [[ "${GITHUB_REF_NAME}" == 'main' ]]; then
            EXPO_PUBLIC_APP_VARIANT=dev EXPO_PUBLIC_URL=http://129.213.146.93:9083 EXPO_PUBLIC_ANDROID_CLIENT_ID=${{ secrets.DEV_ANDROID_CLIENT_ID }} eas update --branch dev --message "${COMMIT_MESSAGE}"
          elif [[ "${GITHUB_REF_NAME}" == 'qa' ]]; then
            EXPO_PUBLIC_APP_VARIANT=qa EXPO_PUBLIC_URL=http://129.213.146.93:9083 EXPO_PUBLIC_ANDROID_CLIENT_ID=${{ secrets.QA_ANDROID_CLIENT_ID }} eas update --auto
          elif [[ "${GITHUB_REF_NAME}" == 'production' ]]; then
            EXPO_PUBLIC_APP_VARIANT=prod EXPO_PUBLIC_URL=http://140.245.21.83:8090 EXPO_PUBLIC_ANDROID_CLIENT_ID=${{ secrets.PROD_ANDROID_CLIENT_ID }} eas update --auto
          else
            echo "Branch not configured for EAS update."
          fi
