name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - CI_CD
jobs:
  build:
    name: Install, test, and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build on EAS
        run: eas build --profile production --platform android --non-interactive --no-wait
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Your APK is ready
          body: The APK build has been completed successfully.
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
