name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - qa
      - production
jobs:
  build:
    name: Install, test, and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build on EAS
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)  # Get the current branch name
          if [ "$BRANCH_NAME" = "main" ]; then
             PROFILE="dev"
          else
             PROFILE="$BRANCH_NAME"
          fi          
          BUILD_URL=$(eas build --profile $PROFILE --platform android --non-interactive --no-wait | grep -o 'https://expo.dev/accounts/[^ ]*')
          echo $BUILD_URL > build_url.txt
      - name: Get build URL
        id: get_url
        run: |
          echo "::set-output name=URL::$(cat build_url.txt)"
      - name: Construct email body
        id: email_body
        run: |
          echo "::set-output name=BODY::The APK build has been triggered successfully. You can download it from the following URL after completion: $(cat build_url.txt)"
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Your APK build is triggered
          body: ${{ steps.email_body.outputs.BODY }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
